name: Test
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@2.1.4
        with:
          node_version: 12
      - run: npm ci
      - run: npm test
      - run: npm run build
        
